version: '2'
services:
  bankdb:
    image: mysql
    ports:
      - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arqsoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: appbankDev
      MYSQL_HOST: bankdb
  bankms:
    build: .
    command: bash -c "sleep 50 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 5000 -b '0.0.0.0'"
    ports:
      - "5000:5000"
    depends_on:
      - bankdb